# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline'),
        ),
    ]
